In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class Block:
    def __init__(self) -> None:
        self.block = np.random.choice([0, 1])

In [3]:
l = lambda x: x.block
vec_l = np.vectorize(l)

In [4]:
N = 1_000

a = np.array(
    [Block() for i in range(N)]
)

In [5]:
c = 0
for i in range(N):
    if a[i].block == 1:
        c+=1
print(c)

484


In [6]:
np.sum(vec_l(a))

484

In [7]:
l1 = lambda i, j: i*j
vec_l1 = np.vectorize(l1)

In [8]:
xy = np.array([
    [0, 0],
    [1, 0],
    [2, 1],
])

In [9]:
xy[:, 0]

array([0, 1, 2])

In [10]:
vec_l1(xy[:, 0], xy[:, 1])

array([0, 0, 2])

In [11]:
d = {
    'a': 4,
    'b': 4,
    'c': 4,
}

In [12]:
for i, c in enumerate(d):
    print(i, c)

0 a
1 b
2 c


In [13]:
zip(d)

In [21]:
a = np.array([
    [1,1],
    [1,2],
    [1,3],
    [1,4],
    [1,5],
    [1,6],
    
])

In [22]:
a[]

SyntaxError: invalid syntax (1145722274.py, line 1)

In [39]:
[[1,1] [1,2]] == a

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\357244317.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[1,1] [1,2]] == a
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\357244317.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[1,1] [1,2]] == a
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\357244317.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[1,1] [1,2]] == a


TypeError: list indices must be integers or slices, not tuple

In [38]:
np.all([[1,1] [1,2]] == a, axis=1)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\3493587461.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.all([[1,1] [1,2]] == a, axis=1)
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\3493587461.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.all([[1,1] [1,2]] == a, axis=1)
C:\Users\ovann\AppData\Local\Temp\ipykernel_8032\3493587461.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.all([[1,1] [1,2]] == a, axis=1)


TypeError: list indices must be integers or slices, not tuple

In [32]:
np.argwhere(np.all((1,1) == a, axis=1))

array([[0]], dtype=int64)

In [33]:
a[np.argwhere(np.all((1,1) == a, axis=1))[0]]

array([[1, 1]])

In [36]:
np.delete(a, np.argwhere(np.all((1,1) == a, axis=1))[0], axis=0)

array([[1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6]])