In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
np.random.seed(42)
np.random.randint(0, 1+1, (16, 16))

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]])

In [49]:
rng = np.random.default_rng(42)
region_map = rng.integers(0, 1+1, (16, 16))

region_map

array([[0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [96]:
road_map = rng.choice([0, 1], (16, 16), p=[0.95, 0.05])

road_map_new = road_map
for r in rng.choice([(0,1), (1,0)], 10):
    road_map_new = road_map_new | np.roll(road_map, r*rng.integers(0, 10), axis=(0, 1))

road_map = road_map_new
road_map

array([[1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0]])

In [100]:
rng = np.random.default_rng(42)
region_map = rng.integers(0, 1+1, (16, 16))

road_map = rng.choice([0, 1], (16, 16), p=[0.95, 0.05])
road_map_new = road_map
for r in rng.choice([(0,1), (1,0)], 10):
    road_map_new = road_map_new | np.roll(road_map, r*rng.integers(0, 10), axis=(0, 1))
road_map = road_map_new
region_map[road_map == 1] = 2

region_map

array([[2, 1, 1, 0, 0, 1, 0, 1, 2, 2, 2, 1, 1, 1, 2, 1],
       [1, 0, 1, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0],
       [0, 2, 1, 0, 1, 2, 0, 1, 2, 2, 2, 2, 0, 1, 0, 2],
       [1, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1],
       [0, 2, 1, 0, 0, 0, 1, 0, 2, 2, 2, 2, 0, 0, 1, 2],
       [2, 2, 0, 1, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 1, 2],
       [2, 1, 1, 0, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 2, 2],
       [1, 2, 1, 1, 0, 0, 0, 0, 2, 2, 1, 0, 1, 1, 0, 1],
       [1, 2, 1, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0],
       [1, 2, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1, 1, 2],
       [2, 1, 0, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2],
       [1, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 2],
       [1, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2],
       [1, 0, 1, 1, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)